### ISSUE TITLE
Same board for Congo Bongo?

### ISSUE THREAD

**Issue by Gdsimms** [MiSTer-devel/Arcade-Zaxxon_MiSTer#7]
From what I can tell searching around online, it's possible Congo Bongo uses the same board as Zaxxon. Would that make it easy or at least possible to use this core with Congo Bongo ROMs?

**Comment by alanswx** [comment]
Future Spy is next - it is working on Gehstock's MiST repo, the changes need to be merged. From mame about Congo Bong:
/* these games run on a slightly newer Zaxxon hardware with more ROM space and a */
/* custom sprite DMA chip */

**Comment by SwedishGojira** [comment]
No updates on supporting this? This is a great Sega classic I feel really is missing on the MiSTer.

**Comment by darfpga** [comment]
Congo Bongo is available now as a separate core.
