### ISSUE TITLE
Colors in Zaxxon/Super Zaxxon are off

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/Arcade-Zaxxon_MiSTer#9]
See attached pictures for examples:

![20210209_225907-screen](https://user-images.githubusercontent.com/60025144/107586625-23def900-6bb5-11eb-929e-64255f32573b.png)
![20210209_225748-screen](https://user-images.githubusercontent.com/60025144/107586629-24778f80-6bb5-11eb-9dc6-a6a2444c3edc.png)
![20210209_225754-screen](https://user-images.githubusercontent.com/60025144/107586630-24778f80-6bb5-11eb-95b9-6e4112ca5e0f.png)
![20210209_225758-screen](https://user-images.githubusercontent.com/60025144/107586631-24778f80-6bb5-11eb-83ef-e01ea6c9484c.png)
![20210209_225903-screen](https://user-images.githubusercontent.com/60025144/107586632-25102600-6bb5-11eb-9cee-483cb7f6da71.png)

![20210209_225600-screen](https://user-images.githubusercontent.com/60025144/107586536-fbef9580-6bb4-11eb-8761-a2d7b1103119.png)
![20210209_225605-screen](https://user-images.githubusercontent.com/60025144/107586540-fd20c280-6bb4-11eb-848a-876b5068bd0d.png)
![20210209_225617-screen](https://user-images.githubusercontent.com/60025144/107586542-fdb95900-6bb4-11eb-98e3-422b2b47c693.png)

**Comment by Brianvgplayer** [comment]
Maybe something got mixed up? Future Spy is now loading Zaxxon's samples and Zaxxon is also loading the wrong samples.

**Comment by JimmyStones** [comment]
> Maybe something got mixed up? Future Spy is now loading Zaxxon's samples and Zaxxon is also loading the wrong samples.

Hi @Brianvgplayer - can you confirm this is still an issue with the latest update?  They seem ok to me now but then they are all very similar!

@thepulserifle - the colours should be fixed now :)

**Comment by Brianvgplayer** [comment]
I'll check, but I realized that I may have been mistaken with the sounds.

**Comment by thepulserifle** [comment]
Colors have been restored! Thank you my dude!
